package charger

// Code generated by github.com/andig/cmd/tools/decorate.go. DO NOT EDIT.

import (
	"github.com/andig/evcc/api"
)

func decoratecFosPowerBrain(base *cFosPowerBrain, meter func() (float64, error), meterEnergy func() (float64, error), meterCurrent func() (float64, float64, float64, error), chargerEx func(current float64) error) api.Charger {
	switch {
	case chargerEx == nil && meter == nil && meterCurrent == nil && meterEnergy == nil:
		return base

	case chargerEx == nil && meter != nil && meterCurrent == nil && meterEnergy == nil:
		return &struct {
			*cFosPowerBrain
			api.Meter
		}{
			cFosPowerBrain: base,
			Meter: &decoratecFosPowerBrainMeterImpl{
				meter: meter,
			},
		}

	case chargerEx == nil && meter == nil && meterCurrent == nil && meterEnergy != nil:
		return &struct {
			*cFosPowerBrain
			api.MeterEnergy
		}{
			cFosPowerBrain: base,
			MeterEnergy: &decoratecFosPowerBrainMeterEnergyImpl{
				meterEnergy: meterEnergy,
			},
		}

	case chargerEx == nil && meter != nil && meterCurrent == nil && meterEnergy != nil:
		return &struct {
			*cFosPowerBrain
			api.Meter
			api.MeterEnergy
		}{
			cFosPowerBrain: base,
			Meter: &decoratecFosPowerBrainMeterImpl{
				meter: meter,
			},
			MeterEnergy: &decoratecFosPowerBrainMeterEnergyImpl{
				meterEnergy: meterEnergy,
			},
		}

	case chargerEx == nil && meter == nil && meterCurrent != nil && meterEnergy == nil:
		return &struct {
			*cFosPowerBrain
			api.MeterCurrent
		}{
			cFosPowerBrain: base,
			MeterCurrent: &decoratecFosPowerBrainMeterCurrentImpl{
				meterCurrent: meterCurrent,
			},
		}

	case chargerEx == nil && meter != nil && meterCurrent != nil && meterEnergy == nil:
		return &struct {
			*cFosPowerBrain
			api.Meter
			api.MeterCurrent
		}{
			cFosPowerBrain: base,
			Meter: &decoratecFosPowerBrainMeterImpl{
				meter: meter,
			},
			MeterCurrent: &decoratecFosPowerBrainMeterCurrentImpl{
				meterCurrent: meterCurrent,
			},
		}

	case chargerEx == nil && meter == nil && meterCurrent != nil && meterEnergy != nil:
		return &struct {
			*cFosPowerBrain
			api.MeterCurrent
			api.MeterEnergy
		}{
			cFosPowerBrain: base,
			MeterCurrent: &decoratecFosPowerBrainMeterCurrentImpl{
				meterCurrent: meterCurrent,
			},
			MeterEnergy: &decoratecFosPowerBrainMeterEnergyImpl{
				meterEnergy: meterEnergy,
			},
		}

	case chargerEx == nil && meter != nil && meterCurrent != nil && meterEnergy != nil:
		return &struct {
			*cFosPowerBrain
			api.Meter
			api.MeterCurrent
			api.MeterEnergy
		}{
			cFosPowerBrain: base,
			Meter: &decoratecFosPowerBrainMeterImpl{
				meter: meter,
			},
			MeterCurrent: &decoratecFosPowerBrainMeterCurrentImpl{
				meterCurrent: meterCurrent,
			},
			MeterEnergy: &decoratecFosPowerBrainMeterEnergyImpl{
				meterEnergy: meterEnergy,
			},
		}

	case chargerEx != nil && meter == nil && meterCurrent == nil && meterEnergy == nil:
		return &struct {
			*cFosPowerBrain
			api.ChargerEx
		}{
			cFosPowerBrain: base,
			ChargerEx: &decoratecFosPowerBrainChargerExImpl{
				chargerEx: chargerEx,
			},
		}

	case chargerEx != nil && meter != nil && meterCurrent == nil && meterEnergy == nil:
		return &struct {
			*cFosPowerBrain
			api.ChargerEx
			api.Meter
		}{
			cFosPowerBrain: base,
			ChargerEx: &decoratecFosPowerBrainChargerExImpl{
				chargerEx: chargerEx,
			},
			Meter: &decoratecFosPowerBrainMeterImpl{
				meter: meter,
			},
		}

	case chargerEx != nil && meter == nil && meterCurrent == nil && meterEnergy != nil:
		return &struct {
			*cFosPowerBrain
			api.ChargerEx
			api.MeterEnergy
		}{
			cFosPowerBrain: base,
			ChargerEx: &decoratecFosPowerBrainChargerExImpl{
				chargerEx: chargerEx,
			},
			MeterEnergy: &decoratecFosPowerBrainMeterEnergyImpl{
				meterEnergy: meterEnergy,
			},
		}

	case chargerEx != nil && meter != nil && meterCurrent == nil && meterEnergy != nil:
		return &struct {
			*cFosPowerBrain
			api.ChargerEx
			api.Meter
			api.MeterEnergy
		}{
			cFosPowerBrain: base,
			ChargerEx: &decoratecFosPowerBrainChargerExImpl{
				chargerEx: chargerEx,
			},
			Meter: &decoratecFosPowerBrainMeterImpl{
				meter: meter,
			},
			MeterEnergy: &decoratecFosPowerBrainMeterEnergyImpl{
				meterEnergy: meterEnergy,
			},
		}

	case chargerEx != nil && meter == nil && meterCurrent != nil && meterEnergy == nil:
		return &struct {
			*cFosPowerBrain
			api.ChargerEx
			api.MeterCurrent
		}{
			cFosPowerBrain: base,
			ChargerEx: &decoratecFosPowerBrainChargerExImpl{
				chargerEx: chargerEx,
			},
			MeterCurrent: &decoratecFosPowerBrainMeterCurrentImpl{
				meterCurrent: meterCurrent,
			},
		}

	case chargerEx != nil && meter != nil && meterCurrent != nil && meterEnergy == nil:
		return &struct {
			*cFosPowerBrain
			api.ChargerEx
			api.Meter
			api.MeterCurrent
		}{
			cFosPowerBrain: base,
			ChargerEx: &decoratecFosPowerBrainChargerExImpl{
				chargerEx: chargerEx,
			},
			Meter: &decoratecFosPowerBrainMeterImpl{
				meter: meter,
			},
			MeterCurrent: &decoratecFosPowerBrainMeterCurrentImpl{
				meterCurrent: meterCurrent,
			},
		}

	case chargerEx != nil && meter == nil && meterCurrent != nil && meterEnergy != nil:
		return &struct {
			*cFosPowerBrain
			api.ChargerEx
			api.MeterCurrent
			api.MeterEnergy
		}{
			cFosPowerBrain: base,
			ChargerEx: &decoratecFosPowerBrainChargerExImpl{
				chargerEx: chargerEx,
			},
			MeterCurrent: &decoratecFosPowerBrainMeterCurrentImpl{
				meterCurrent: meterCurrent,
			},
			MeterEnergy: &decoratecFosPowerBrainMeterEnergyImpl{
				meterEnergy: meterEnergy,
			},
		}

	case chargerEx != nil && meter != nil && meterCurrent != nil && meterEnergy != nil:
		return &struct {
			*cFosPowerBrain
			api.ChargerEx
			api.Meter
			api.MeterCurrent
			api.MeterEnergy
		}{
			cFosPowerBrain: base,
			ChargerEx: &decoratecFosPowerBrainChargerExImpl{
				chargerEx: chargerEx,
			},
			Meter: &decoratecFosPowerBrainMeterImpl{
				meter: meter,
			},
			MeterCurrent: &decoratecFosPowerBrainMeterCurrentImpl{
				meterCurrent: meterCurrent,
			},
			MeterEnergy: &decoratecFosPowerBrainMeterEnergyImpl{
				meterEnergy: meterEnergy,
			},
		}
	}

	return nil
}

type decoratecFosPowerBrainChargerExImpl struct {
	chargerEx func(current float64) error
}

func (impl *decoratecFosPowerBrainChargerExImpl) MaxCurrentMillis(current float64) error {
	return impl.chargerEx(current)
}

type decoratecFosPowerBrainMeterImpl struct {
	meter func() (float64, error)
}

func (impl *decoratecFosPowerBrainMeterImpl) CurrentPower() (float64, error) {
	return impl.meter()
}

type decoratecFosPowerBrainMeterCurrentImpl struct {
	meterCurrent func() (float64, float64, float64, error)
}

func (impl *decoratecFosPowerBrainMeterCurrentImpl) Currents() (float64, float64, float64, error) {
	return impl.meterCurrent()
}

type decoratecFosPowerBrainMeterEnergyImpl struct {
	meterEnergy func() (float64, error)
}

func (impl *decoratecFosPowerBrainMeterEnergyImpl) TotalEnergy() (float64, error) {
	return impl.meterEnergy()
}
